sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty
language: python


matrix:
  include:
    - python: '2.7'
      env: TOXENV="flake8"

    - python: '2.7'
      env: TOXENV="py27"

    - python: '3.5'
      env: TOXENV="py35"

    - python: '3.6'
      env: TOXENV="py36"

install: source continuous_integration/travis/install.sh
script: tox -v
