sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty
language: python


matrix:
  include:
    - env: ONLY_CODESTYLE="yes"
    - env: PYTHON_VERSION="py27" NUMPY_VERSION="1.11.3" SCIPY_VERSION="0.18.1" ONLY_CODESTYLE="no"
    - env: PYTHON_VERSION="py35" NUMPY_VERSION="1.11.3" SCIPY_VERSION="0.18.1" ONLY_CODESTYLE="no"
    - env: PYTHON_VERSION="py36" NUMPY_VERSION="1.11.3" SCIPY_VERSION="0.18.1" ONLY_CODESTYLE="no"


install: source continuous_integration/travis/install.sh
script: bash continuous_integration/travis/run.sh
